name: production deploy

on:
  push:
    branches: [ci-cd]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.18.1
      - run: npm install -g yarn
      - run: yarn
      - run: yarn lint
      - run: yarn build
